apiVersion: v1
kind: Service
metadata:
  name: {{ include "todoapp.fullname" . }}
  labels:
    app: todoapp
    {{- include "todoapp.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: todoapp
    {{- include "todoapp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 8000 }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
